/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mechanical_spider.glb 
Author: vertexmonster (https://sketchfab.com/vertexmonster)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mechanical-spider-87e0a94c2e1f44b5b5c9d088f4d5f4ab
Title: Mechanical Spider
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanical_spider(props) {
  const { nodes, materials } = useGLTF('/models/mechanical_spider.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.spider_mech} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.spider_mech} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mechanical_spider.glb')
